### ISSUE TITLE
Code and Eval dataset releasing

### ISSUE THREAD

**Issue by weleen** [Garfield-kh/TM2D#1]
Hi, TM2D is a fantastic job! I'd like to know when will the code and dataset for testing be available. Thanks!

**Comment by weleen** [comment]
@Garfield-kh

**Comment by Garfield-kh** [comment]
Thank you for the interest and sorry for the late reply.
I was quite busy with working stuff, I am trying cleaning the code currently.

**Comment by Garfield-kh** [comment]
Hi~  code, pretrain weight, and data are ready here.
