### ISSUE TITLE
How to get the text descriptions for dance? 

### ISSUE THREAD

**Issue by luomingshuang** [Garfield-kh/TM2D#10]
Hi, this is a great work. But I don't look at the method that how to get the text descriptions for dance in the paper. Can you help me with this question?

**Comment by Garfield-kh** [comment]
Hi, In this work, we are adding some action instrction like "take a jump, doing a catwheel" during dance. it is not the dance description. But I think there are some motion2text you can try to extract dance-text pair. like what they do in video2text for data  synthesis.
