### ISSUE TITLE
How to convert 22 joints defined by the HumanML3D to 24 joints defined by the AIST++?

### ISSUE THREAD

**Issue by RuiLi2013** [Garfield-kh/TM2D#11]
HumanML3D has 22 joints (no hand joints with indices 22 and 23). AIST++ has full 24 joints. TM2D uses 24 joints, and how do you convert the 22 joints defined by the HumanML3D to the 24 joints defined by the AIST++？

**Comment by Garfield-kh** [comment]
Hi I apply HumanML3D to standard SMPL model and extract the 24 joints (same as the dance dataset).
