### ISSUE TITLE
Where to download  eval4bailando file?

### ISSUE THREAD

**Issue by mengW6** [Garfield-kh/TM2D#12]
I am very honored to see such a great job, and I am trying to reproduce it. There are a  question:
./tm2d_60fps/eval4bailando/     # download from google drive  
 Where can I download  eval4bailando file? I couldn't find it on google drive.

**Comment by mengW6** [comment]
May I ask what graphics card, how much graphics memory, and how many GPUs were used in your code

**Comment by Garfield-kh** [comment]
I think I have put all things into google drive, did you download the very large file?
I use T4 GPU (16GB in my training), motion data does not require much GPU resources.
