### ISSUE TITLE
Training train-a2d-transformer_v5 error

### ISSUE THREAD

**Issue by mengW6** [Garfield-kh/TM2D#13]
Hello, a great piece of work. I encountered an error while trying to reproduce the code. During the process of running  train-a2d-transformer_v5.py, I encountered a RuntimeError: copy_if failed to synchronize: cudaErrorAssert: device side assert triggered.  Do you know why this is happening? If you could help me resolve this, I would greatly appreciate it.

**Comment by Garfield-kh** [comment]
Hi, thank you for the interest.
It seems to be cuda issue, can you try checking the nvidia driver version + cuda version + pytorch version?

**Comment by mengW6** [comment]
Thank you :)
