### ISSUE TITLE
where is the environment?

### ISSUE THREAD

**Issue by Da1yuqin** [Garfield-kh/TM2D#2]
haven't found environment.yaml or the requierments.txt

**Comment by Da1yuqin** [comment]
btw, what's the version of Python?

**Comment by Garfield-kh** [comment]
Hi, thank you for the interest!
The environment is combine the [TM2T](https://github.com/EricGuo5513/TM2T) and [Bailando](https://github.com/lisiyao21/Bailando). You may follow their requirements.txt for the installation.
