### ISSUE TITLE
Question about the evaluation for audio-to-dance?

### ISSUE THREAD

**Issue by blue-blue272** [Garfield-kh/TM2D#4]
In Table1, how to compute the FID and Div? I think the processing can not produce keypoints3D for geometric features and kinetic features.

**Comment by Garfield-kh** [comment]
Hi, thank you for the interest!
We following the evaluation [code ](https://github.com/lisiyao21/Bailando/blob/cc90b98bff81c9709570db413c9610c2562e27ca/utils/metrics_new.py#L80) of [Bailando](https://github.com/lisiyao21/Bailando/tree/main).
