### ISSUE TITLE
How do you show a character model like bailando

### ISSUE THREAD

**Issue by Ohahehe** [Garfield-kh/TM2D#5]
When I run the visualization, all I can see is the skeleton model of the character. But I want to see the character model demonstrated in Project bailando. Can you help me? Thank you very much.

**Comment by Garfield-kh** [comment]
The model is download from [mixamo](https://www.mixamo.com/#/)
And it is rendered by [UNITY ](https://unity.com/)
The character need to be driven by axis-angle, which need to be convert from global joint position by [IK-joints2smpl](https://github.com/wangsen1312/joints2smpl)
You have to know how to use unity on this.

**Comment by Ohahehe** [comment]
> The model is download from [mixamo](https://www.mixamo.com/#/) And it is rendered by [UNITY ](https://unity.com/) The character need to be driven by axis-angle, which need to be convert from global joint position by [IK-joints2smpl](https://github.com/wangsen1312/joints2smpl) You have to know how to use unity on this.

I have now done what you said, and I found that it will generate frame by frame smpl model from my animation. But I want a complete animation process, do I want to use unity to integrate these smpl models into one animation, or? I'm really sorry I don't know how to use UNITY very well. Thank you very much.

**Comment by Garfield-kh** [comment]
yes we use unity for the animation, but the detail is done by others. You may need to explore from other project. some avatar related.
