### ISSUE TITLE
How to get music features from audio_vecs_7.5fps?

### ISSUE THREAD

**Issue by BossunWang** [Garfield-kh/TM2D#6]
Hi expert,
nice work to music-text to control motion, and I have studied code and paper in which music features from librosa, but I only search npy files.
May you tell me how to extract features from librosa?

**Comment by Garfield-kh** [comment]
Hi Thank you for the interest.
The music features if convert by the Bailando python file [_prepro_aistpp_music.py](https://github.com/lisiyao21/Bailando/blob/main/_prepro_aistpp_music.py), which input mp3 music file, and output npy feature file with fps setting.
