### ISSUE TITLE
Question about how to new npy file

### ISSUE THREAD

**Issue by Ohahehe** [Garfield-kh/TM2D#8]
Hi @Garfield-kh , Thanks for your reply to the previous question. And now I have another question. How to get audio features from MP3 text and save them as npy files. I can't find the relevant generation process in your file. Can you tell me how this should be generated, or where the file is. Thank you very much.
The reason is when I new a mp3 file and then I want to extracrt audio feature into npy file. But I encounter a mismatch between the input matrix dimensions and the weight matrix dimensions. I think a lot of this is due to the small dimension size of my npy file. So can you help me ? Thank you very much.

**Comment by Garfield-kh** [comment]
Hi @Ohahehe ,
The music features is converted by the Bailando python file [_prepro_aistpp_music.py](https://github.com/lisiyao21/Bailando/blob/main/_prepro_aistpp_music.py), which input mp3 music file, and output npy feature file with fps setting.
