### ISSUE TITLE
Audio tokenizer

### ISSUE THREAD

**Issue by YvonneLiuym** [Garfield-kh/TM2D#9]
Hi, congrats on your great work!
In `dataset.py`, there is `opt.tokenizer_name_audio`. I wonder if you can share how you obtained tokenized audio in the aistpp dataset. Thanks!

**Comment by Garfield-kh** [comment]
hi, thank you for the interest!
We do try tokenize the music in audio2dance task, however, it seems like it is not perform as good as audio vector, so this was ignored in the later experiment.
